const lessonData = {};

lessonData["01_GlassWindowTester.mp3"] = [{
    text: "1. The Glass Window Tester. Garry was a very successful lawyer in Canada. He worked in a very tall office building in the big city. Garry loved his office very much. He was always very proud of the building's strong glass windows. He wanted to show everyone that the thick windows were completely safe and could never break. One day, some young university students visited his office on the twenty-fourth floor. Garry wanted to impress them with a funny trick. He ran very fast across the room and jumped heavily against the big glass window. He did this all the time to prove a point. Amazingly, the thick glass did not break at all. But Garry made a terrible and deadly mistake. The heavy glass stayed in one perfect piece, but the whole window popped completely out of the metal frame! Garry and the heavy window fell twenty-four floors down to the street. He wanted to prove the glass was strong, and he was absolutely right. The glass never broke. However, his silly trick cost him his life because he forgot to check the window frame.",
    dict: { "successful": "başarılı", "lawyer": "avukat", "proud": "gururlu", "thick": "kalın", "safe": "güvenli", "impress": "etkilemek", "trick": "numara", "heavily": "ağır bir şekilde", "prove": "kanıtlamak", "Amazingly": "şaşırtıcı bir şekilde", "deadly": "ölümcül", "popped": "yerinden fırladı", "frame": "çerçeve", "street": "sokak", "absolutely": "kesinlikle", "forgot": "unuttu" },
    questions: [ {q:"Was Garry a successful lawyer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he work on the twenty-fourth floor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to impress the students?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he jump against the glass window?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the thick glass break?", a_en:"No", a_tr:"Hayır"}, {q:"Did the window pop out of the metal frame?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Garry forget to check the frame?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_GiantCactusAttacker.mp3"] = [{
    text: "2. The Giant Cactus Attacker. David was a young man who lived near the hot desert in America. He and his good friend wanted to have some fun one day. They took their hunting guns and drove into the dry desert to shoot some plants. They found a very old and incredibly huge Saguaro cactus. These green desert plants can grow to be extremely tall and heavy. They can live for hundreds of years in the dry sand. David decided to attack the biggest cactus he could find. It was almost thirty feet tall! He stood very close to the giant plant and shot it many times with his gun. He was having a lot of fun, but he did not think about basic gravity. Because he shot the bottom of the plant, a massive piece of the heavy cactus broke off. The huge, heavy green piece with thousands of sharp needles fell straight down. It fell directly on top of David and crushed him instantly. He wanted to fight a quiet, peaceful plant, but the giant desert plant easily won the battle.",
    dict: { "desert": "çöl", "hunting guns": "av tüfekleri", "shoot": "ateş etmek", "incredibly": "inanılmaz derecede", "huge": "kocaman", "sand": "kum", "attack": "saldırmak", "gravity": "yerçekimi", "bottom": "alt/dip", "massive": "devasa", "needles": "iğneler/dikenler", "straight": "dosdoğru", "crushed": "ezdi", "instantly": "anında", "peaceful": "huzurlu/barışçıl" },
    questions: [ {q:"Did David live near the hot desert?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to shoot some plants?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the cactus very small?", a_en:"No", a_tr:"Hayır"}, {q:"Did he shoot the bottom of the plant?", a_en:"Yes", a_tr:"Evet"}, {q:"Did David think about basic gravity?", a_en:"No", a_tr:"Hayır"}, {q:"Did a heavy piece of the cactus fall on him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the quiet plant win the battle?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_AngryLetterSender.mp3"] = [{
    text: "3. The Angry Letter Sender. This story is about a very angry and dangerous man, but he was also incredibly stupid. In the year nineteen ninety-nine, a bad man wanted to hurt someone he hated very much. He decided to make a dangerous bomb and put it inside a normal paper envelope. He wrote the enemy's home address on the front of the envelope. He planned to send the bad letter through the regular post office. However, he was very careless and did not put enough stamps on the envelope to pay for the delivery. He put the letter in a post box and went back home. The post office workers saw that the letter did not have enough stamps. Because it did not have enough stamps, they kindly returned the letter to the sender's house. A few days later, the angry man received a letter in his own mailbox. He completely forgot his own evil plan. He happily opened the envelope to read the letter, and his own bomb exploded. His terrible plan failed completely because he forgot to buy enough cheap stamps.",
    dict: { "dangerous": "tehlikeli", "hated": "nefret etti", "bomb": "bomba", "envelope": "zarf", "enemy": "düşman", "careless": "dikkatsiz", "stamps": "pullar", "delivery": "teslimat", "returned": "iade etti", "sender": "gönderici", "received": "aldı", "evil": "kötü", "happily": "mutlulukla", "exploded": "patladı", "cheap": "ucuz" },
    questions: [ {q:"Did the man want to hurt his enemy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he put a bomb inside an envelope?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he put enough stamps on the envelope?", a_en:"No", a_tr:"Hayır"}, {q:"Did the post office return the letter to him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he remember his own evil plan?", a_en:"No", a_tr:"Hayır"}, {q:"Did he open the envelope happily?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his own bomb explode?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_BadBungeeJumper.mp3"] = [{
    text: "4. The Bad Bungee Jumper. Eric was an adventurous young man who loved dangerous sports and exciting activities. He worked at a local restaurant and decided he wanted to try bungee jumping. Bungee jumping is when you jump from a very high place with a strong elastic rope tied to your feet. The rope stops you safely before you hit the ground. Eric wanted to jump off a very tall train bridge in his town. He was a smart worker, so he carefully measured the height of the bridge. He found out the bridge was exactly seventy feet high. Then, he went to a sports store and bought exactly seventy feet of strong bungee rope. He tied the rope to his feet and jumped off the tall bridge. But he forgot one very important detail about bungee ropes. Bungee ropes are elastic, which means they stretch and get much longer when you pull them! Because he bought seventy feet of rope for a seventy-foot bridge, the rope stretched much further when he jumped. He hit the hard ground heavily and died immediately.",
    dict: { "adventurous": "maceracı", "exciting": "heyecan verici", "elastic": "esnek", "tied": "bağlı", "safely": "güvenle", "bridge": "köprü", "measured": "ölçtü", "height": "yükseklik", "exactly": "tam olarak", "bought": "satın aldı", "detail": "detay", "stretch": "esnemek/uzamak", "further": "daha ileri", "ground": "yer/zemin", "immediately": "derhal" },
    questions: [ {q:"Was Eric an adventurous man?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he measure the height of the bridge?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the bridge seventy feet high?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he buy exactly seventy feet of rope?", a_en:"Yes", a_tr:"Evet"}, {q:"Do elastic ropes stretch and get longer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he hit the hard ground?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he remember the important detail about elastic ropes?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["05_CarelessMetalThief.mp3"] = [{
    text: "5. The Careless Metal Thief. In the year nineteen ninety-eight, a man in America decided to steal a heavy metal fence. He saw a beautiful and expensive iron fence in front of a big company building. He wanted to take the heavy metal and sell it to make some fast money. He brought his tools and started working very late at night when it was dark and quiet. The fence was very tall and extremely heavy. He worked hard to take out all the bolts and screws that held the fence to the ground. He was so excited about the money that he did not think about basic physics. He unbolted every single piece of the heavy fence while he was still standing directly underneath it! When he removed the very last bolt, the massive iron fence had nothing to hold it up anymore. The entire heavy metal structure fell over and completely crushed the silly thief. The police found him the next morning. He died trying to steal something that was much too heavy and dangerous for him to handle alone.",
    dict: { "steal": "çalmak", "fence": "çit", "expensive": "pahalı", "tools": "aletler", "bolts": "cıvatalar", "screws": "vidalar", "physics": "fizik", "unbolted": "cıvatalarını söktü", "underneath": "altında", "removed": "çıkardı", "structure": "yapı", "crushed": "ezdi", "thief": "hırsız", "handle": "başa çıkmak/idare etmek" },
    questions: [ {q:"Did the man want to steal an iron fence?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the fence very tall and heavy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he work late at night?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he unbolt the fence while standing underneath it?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he think about basic physics?", a_en:"No", a_tr:"Hayır"}, {q:"Did the entire structure fall over?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the heavy fence crush the thief?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_LavaLampHeater.mp3"] = [{
    text: "6. The Lava Lamp Heater. Philip was a young man who lived in America. He had a beautiful lava lamp in his bedroom. Lava lamps are glass bottles with colored wax inside. When the lamp gets warm, the wax moves up and down like magic. One day, Philip wanted his lava lamp to get warm very quickly. He did not want to wait for the normal small lightbulb to heat it. So, he made a very stupid decision. He took the glass lava lamp and put it directly on his hot kitchen stove! He turned on the fire to heat the glass bottle fast. But glass and hot wax are a very dangerous combination on a hot stove. The liquid inside the glass bottle got too hot too fast. The pressure grew very high inside the bottle. Suddenly, the entire glass lamp exploded with a huge, loud bang. A sharp piece of the heavy glass flew quickly across the room. It hit Philip directly in his chest, and he died. He just wanted to watch the pretty wax move, but he forgot basic science and lost his life.",
    dict: { "wax": "balmumu/vaks", "warm": "ılık/sıcak", "lightbulb": "ampul", "heat": "ısıtmak", "decision": "karar", "stove": "ocak", "combination": "kombinasyon", "liquid": "sıvı", "pressure": "basınç", "exploded": "patladı", "bang": "patlama sesi", "sharp": "keskin", "chest": "göğüs", "science": "bilim" },
    questions: [ {q:"Did Philip have a lava lamp in his bedroom?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want the lamp to get warm quickly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he put the glass lamp on a hot stove?", a_en:"Yes", a_tr:"Evet"}, {q:"Is hot wax and glass safe on a hot stove?", a_en:"No", a_tr:"Hayır"}, {q:"Did the pressure grow very high inside the bottle?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the glass lamp explode?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a piece of glass hit him in the chest?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_VendingMachineShaker.mp3"] = [{
    text: "7. The Vending Machine Shaker. Kevin was a hungry university student who just wanted a small sweet snack. He walked up to a large vending machine in his school to buy some candy. He put his coins into the machine and pressed the buttons. The machine pushed the candy forward, but the candy got stuck behind the front glass. It did not fall down to the bottom. Kevin was very angry that he lost his money and did not get his food. He decided to fight the machine. These snack machines are incredibly heavy, weighing hundreds of pounds. Kevin grabbed the top of the machine and started shaking it very hard. He rocked it back and forth to make the candy fall. He rocked it too far forward. The massive, heavy machine tipped over and fell completely on top of him. The machine was much too heavy for him to push away. He was crushed to death because he lost his temper over a very cheap piece of candy. It is a very common but very stupid way to die. He made a huge mistake.",
    dict: { "vending machine": "otomat makinesi", "snack": "atıştırmalık", "coins": "bozuk paralar", "stuck": "sıkışmış", "bottom": "alt/dip", "weighing": "ağırlığında", "grabbed": "tuttu/yakaladı", "shaking": "sallama", "rocked": "salladı/hareket ettirdi", "back and forth": "ileri geri", "tipped over": "devrildi", "crushed": "ezildi", "temper": "sinir/öfke", "cheap": "ucuz" },
    questions: [ {q:"Did Kevin want to buy some candy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the candy get stuck behind the glass?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Kevin very happy about this?", a_en:"No", a_tr:"Hayır"}, {q:"Did he start shaking the heavy machine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the massive machine tip over?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he push the heavy machine away?", a_en:"No", a_tr:"Hayır"}, {q:"Did he lose his temper over a cheap candy?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_DynamiteDogFetcher.mp3"] = [{
    text: "8. The Dynamite Dog Fetcher. A man went out to a completely frozen lake in the middle of winter to go fishing. He brought his loyal, happy dog with him for company. He also brought a stick of dangerous dynamite. He wanted to throw the explosive dynamite onto the thick ice to blast a hole in it so he could fish. He stood on the ice, lit the short fuse of the dynamite, and threw it far away. But his dog loved to play games. The dog thought the dynamite was a normal wooden stick! The happy dog ran across the ice, picked up the burning explosive in his mouth, and ran happily back to his owner. The man was completely terrified. He started running away as fast as he could, yelling at the dog to drop the stick. But the loyal dog just chased his owner, thinking it was a fun game of tag. The dog caught up to the man right as the dynamite exploded. Both the man and his poor dog died because the man wanted to cheat at winter fishing.",
    dict: { "frozen": "donmuş", "loyal": "sadık", "dynamite": "dinamit", "explosive": "patlayıcı", "blast": "patlatmak", "fuse": "fitil", "threw": "fırlattı", "wooden": "tahta/ahşap", "burning": "yanan", "owner": "sahip", "terrified": "dehşete düşmüş", "yelling": "bağırarak", "drop": "bırakmak", "chased": "kovaladı", "caught up": "yetişti", "cheat": "hile yapmak" },
    questions: [ {q:"Did the man go to a frozen lake to fish?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he bring dangerous dynamite with him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he throw the dynamite onto the ice?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog think it was a normal wooden stick?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the dog run away from his owner?", a_en:"No", a_tr:"Hayır"}, {q:"Did the dog carry the explosive back to the man?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man try to cheat at winter fishing?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_AngryWheelchairDriver.mp3"] = [{
    text: "9. The Angry Wheelchair Driver. This story is about an angry man who let his bad temper ruin his entire life. A man in a motorized wheelchair was waiting for an elevator inside a tall shopping center in South Korea. The elevator doors opened, but a woman walked in quickly, and the doors closed before the man could enter. The man became completely furious. He backed up his heavy electric wheelchair to get a very good start. Then, he drove forward at full speed and crashed his wheelchair into the metal elevator doors! The doors bent a little bit, but they did not open. He backed up and angrily crashed into the metal doors a second time. The doors bent a little more. Finally, he crashed into the doors a third time with all his power. This time, the metal doors broke open completely. But the elevator car was already gone. There was only an empty, dark hole. The angry man and his heavy electric wheelchair fell straight down the deep elevator shaft to his death. He died because he could not wait two minutes.",
    dict: { "temper": "sinir/öfke", "ruin": "mahvetmek", "wheelchair": "tekerlekli sandalye", "elevator": "asansör", "furious": "öfkeli", "backed up": "geri gitti", "speed": "hız", "crashed": "çarptı", "bent": "büküldü", "power": "güç", "empty": "boş", "hole": "delik", "shaft": "boşluk/şaft" },
    questions: [ {q:"Was the man waiting for an elevator?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the doors close before he could enter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become furious?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he crash his wheelchair into the doors?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the doors break open on the third crash?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the elevator car still there?", a_en:"No", a_tr:"Hayır"}, {q:"Did he fall down the deep elevator shaft?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_GunSafetyTeacher.mp3"] = [{
    text: "10. The Gun Safety Teacher. A man in Texas wanted to teach his close friends about basic gun safety. He was a professional instructor, and he always told people to be very careful with dangerous weapons. One evening, he was drinking alcohol with his friends at a fun party. He picked up his handgun to show them an important lesson. He told his friends that the gun was completely empty and totally safe. To prove it, he did the most stupid thing possible. He pointed the gun directly at his own head. He wanted to pull the trigger to show that nothing would happen. But he made a terrible and deadly mistake. He did not check the weapon properly before the lesson. There was still one real bullet hidden inside the gun. When he pulled the trigger, the gun fired immediately, and he died right in front of all his friends. He wanted to be a smart teacher, but his foolish confidence and his failure to follow his own simple safety rules cost him his life. He should have been much smarter.",
    dict: { "safety": "güvenlik", "instructor": "eğitmen", "weapons": "silahlar", "handgun": "tabanca", "empty": "boş", "prove": "kanıtlamak", "pointed": "doğrulttu", "trigger": "tetik", "mistake": "hata", "properly": "düzgünce", "bullet": "mermi", "hidden": "gizli", "fired": "ateş aldı", "confidence": "özgüven", "failure": "başarısızlık" },
    questions: [ {q:"Was the man a professional instructor?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell his friends the gun was empty?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he point the gun at his own head?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he check the weapon properly before the lesson?", a_en:"No", a_tr:"Hayır"}, {q:"Was there a real bullet inside the gun?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the gun fire when he pulled the trigger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his foolish confidence cost him his life?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["11_BearPhotographer.mp3"] = [{
    text: "11. The Bear Photographer. People often forget that wild forest animals are very dangerous and unpredictable. A man was driving his car through a green forest when he saw a huge, wild brown bear near the road. The man thought the bear looked cute and friendly. He wanted to take a perfect photograph to show his friends back home. He stopped his car, took his camera, and walked very close to the large animal. The bear was busy looking for food and did not want to be bothered by humans. The man walked closer and closer until he was standing right next to the wild beast. He raised his camera to take the picture. The wild bear felt threatened by the stranger in its home. The heavy bear suddenly attacked the man with its sharp claws and incredibly strong teeth. The man died quickly because he thought a wild, dangerous forest animal was just like a gentle pet dog. He risked his entire life just to get a cool photo for his friends to see. This was a very foolish decision.",
    dict: { "unpredictable": "öngörülemez", "cute": "sevimli", "friendly": "arkadaş canlısı", "photograph": "fotoğraf", "bothered": "rahatsız edilmiş", "beast": "canavar/hayvan", "threatened": "tehdit edilmiş", "stranger": "yabancı", "claws": "pençeler", "gentle": "nazik/uysal", "risked": "riske attı", "foolish": "aptalca" },
    questions: [ {q:"Did the man think the bear was cute?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear want to be bothered?", a_en:"No", a_tr:"Hayır"}, {q:"Did the man walk close to the bear?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear feel threatened?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bear attack the man?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the man think the bear was a pet dog?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it a foolish decision?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_TrainSelfieTaker.mp3"] = [{
    text: "12. The Train Selfie Taker. In the modern world, many people die while trying to take a cool photo of themselves with their mobile phones. These pictures are called selfies. A young man in Europe wanted to take an exciting and dangerous selfie to post on the internet. He went to a local train station very late at night. He completely ignored all the warning signs. He climbed all the way to the top of a parked train car. He stood up tall on the roof of the train and held his phone high in the air to get a good angle. But he did not look above his head. Right above the train were thick cables carrying massive amounts of high-voltage electricity. When he raised his arm to take the photo, his hand touched the live electrical wire. A huge shock of strong electricity went through his body immediately. He died instantly, falling off the high train roof. He traded his whole life for a picture that no one ever saw. He should have stayed safely on the ground that night.",
    dict: { "selfies": "özçekimler", "ignored": "görmezden geldi", "warning signs": "uyarı işaretleri", "climbed": "tırmandı", "roof": "çatı", "angle": "açı", "above": "üstünde", "cables": "kablolar", "high-voltage": "yüksek gerilim", "touched": "dokundu", "wire": "tel/kablo", "shock": "şok", "instantly": "anında", "traded": "takas etti" },
    questions: [ {q:"Did he want to take a dangerous selfie?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he ignore the warning signs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he climb on the train roof?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he look above his head?", a_en:"No", a_tr:"Hayır"}, {q:"Did he touch an electrical wire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive the shock?", a_en:"No", a_tr:"Hayır"}, {q:"Did anyone ever see the picture?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["13_SnakePreacher.mp3"] = [{
    text: "13. The Snake Preacher. Some extreme religious groups in America have a very strange and dangerous church tradition. The preachers believe that if they are truly good people, God will protect them from deadly poison. During their church services, they dance and sing while holding live, highly venomous snakes in their bare hands. One famous snake-handling preacher had been bitten many times before, but he always survived and refused to go to a hospital. He thought he was completely invincible. One Sunday, he was holding a very dangerous rattlesnake during a busy church meeting. The snake was stressed and angry because of the loud music. It bit the preacher deeply on the hand, injecting a large amount of deadly venom. The preacher smiled and told everyone he would be fine. He went home and refused to see a real doctor or get any medicine. A few hours later, the terrible snake poison stopped his heart, and he died. His dangerous tradition finally caught up with his foolish pride. He learned too late that wild animals do not care about human beliefs.",
    dict: { "religious": "dini", "tradition": "gelenek", "protect": "korumak", "poison": "zehir", "venomous": "zehirli", "bare hands": "çıplak eller", "survived": "hayatta kaldı", "invincible": "yenilmez", "stressed": "stresli", "injecting": "enjekte ederek", "venom": "yılan zehiri", "refused": "reddetti", "medicine": "ilaç", "pride": "gurur" },
    questions: [ {q:"Did the preachers believe God would protect them?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the preacher hold venomous snakes in his hands?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the snake bite him during the music?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the preacher go to the hospital?", a_en:"No", a_tr:"Hayır"}, {q:"Did he refuse to get medicine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the poison stop his heart?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he survive the snake bite?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["14_TerroristTrainingClass.mp3"] = [{
    text: "14. The Terrorist Training Class. In the year two thousand fourteen, a group of dangerous terrorists in Iraq were attending a secret training camp. They were learning how to build bad bombs and plan violent attacks. The teacher of the class was supposed to be a top expert with explosives. He stood at the front of the room with a special belt completely full of dangerous explosive powder. He was showing his students how to wear the belt and how to connect the wires properly to make a bomb work. There were twenty-one eager students watching him closely in the small room. But the expert teacher made a very simple and deadly mistake with the small wires. He accidentally connected the wrong wire while he was still explaining the lesson to the class. The entire bomb belt exploded instantly with a massive blast. The foolish teacher completely blew himself up, and he also killed all twenty-one of his bad students at the exact same time. It was a perfect Darwin Award for terrible people. They all died because of one small mistake.",
    dict: { "terrorists": "teröristler", "attending": "katılan", "secret": "gizli", "explosives": "patlayıcılar", "belt": "kemer", "powder": "toz", "connect": "bağlamak", "wires": "kablolar", "eager": "istekli/hevesli", "mistake": "hata", "accidentally": "yanlışlıkla", "explaining": "açıklarken", "blast": "patlama", "exact same time": "tam aynı zamanda" },
    questions: [ {q:"Was the teacher an expert with explosives?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he wearing a belt full of explosive powder?", a_en:"Yes", a_tr:"Evet"}, {q:"Were twenty-one students watching him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he connect the wrong wire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the belt explode?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the teacher survive?", a_en:"No", a_tr:"Hayır"}, {q:"Did all the students die too?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_ZooTigerInvader.mp3"] = [{
    text: "15. The Zoo Tiger Invader. Zoos build very high fences to keep dangerous wild animals safe from humans, and to keep humans safe from the animals. A young man visited a zoo in India and saw the beautiful white tiger enclosure. The tiger was resting quietly in its green grass. The man decided he wanted to get a much closer look. He completely ignored all the warning signs. He climbed over the tall fence and jumped down into the deep tiger area. The large white tiger immediately saw the man and walked over to him. The man suddenly realized he was trapped with a massive, dangerous predator. He pressed his back against the wall and looked terrified. The zoo workers yelled at the tiger and threw sticks to try and scare it away. But the loud noise only made the tiger angry and stressed. The huge animal grabbed the young man by the neck and dragged him away like a small toy. The man died because he climbed into a wild tiger's home. He should have respected the basic rules of nature.",
    dict: { "fences": "çitler", "enclosure": "çevrili alan", "ignored": "görmezden geldi", "warning signs": "uyarı işaretleri", "climbed over": "üzerinden tırmandı", "trapped": "kapana kısılmış", "predator": "yırtıcı", "terrified": "dehşete düşmüş", "yelled": "bağırdı", "sticks": "sopalar", "scare away": "korkutup kaçırmak", "dragged": "sürükledi", "respected": "saygı duydu" },
    questions: [ {q:"Did the man ignore the warning signs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he climb over the tall fence?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he jump into the tiger area?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the man trapped with a dangerous predator?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the zoo workers throw sticks at the tiger?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the noise make the tiger angry?", a_en:"Yes", a_tr:"Evet"}, {q:"Should he have respected nature's rules?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_FlyingPriest.mp3"] = [{
    text: "16. The Flying Priest. Father Adelir was a religious priest in Brazil who wanted to raise money for a special charity. He had a very creative but terrible idea. He decided to fly high into the sky using hundreds of normal, colorful helium party balloons. He tied exactly one thousand bright balloons to a special lawn chair. He put on a warm suit, grabbed a parachute, and sat in the comfortable chair. He floated high up into the sky very quickly. But he made a huge mistake before he left. He did not know how to use his GPS navigation machine, and he did not check the strong wind patterns. The fast wind blew him far out over the deep, dangerous ocean. He called for help on his radio, but the rescue helicopters could not find his small chair in the massive sky. He floated higher and higher until the balloons started to pop in the cold air. He fell into the ocean and died. He wanted to help people, but his foolish plan ended in a tragedy. He lost everything.",
    dict: { "priest": "rahip", "raise money": "para toplamak", "charity": "hayır kurumu", "creative": "yaratıcı", "balloons": "balonlar", "lawn chair": "bahçe sandalyesi", "parachute": "paraşüt", "floated": "havalandı/yüzdü", "wind patterns": "rüzgar akımları", "ocean": "okyanus", "rescue": "kurtarma", "pop": "patlamak", "tragedy": "trajedi" },
    questions: [ {q:"Did the priest want to raise money for charity?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tie balloons to a lawn chair?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he float high into the sky?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he check the strong wind patterns?", a_en:"No", a_tr:"Hayır"}, {q:"Did the wind blow him over the dangerous ocean?", a_en:"Yes", a_tr:"Evet"}, {q:"Could the rescue helicopters find him?", a_en:"No", a_tr:"Hayır"}, {q:"Did the balloons pop in the cold air?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_GrenadeGame.mp3"] = [{
    text: "17. The Grenade Game. Two young men in Russia found a very old, unexploded hand grenade in an empty field. Instead of calling the police or running away from the huge danger, they picked it up. They thought it would be fun to play a silly game. They took out their mobile phones and started taking funny pictures with the dangerous weapon. Then, they decided to take the metal pin out of the grenade just to take one final, scary photograph. The metal pin is the only thing that stops a grenade from exploding. They pulled the pin, held the grenade between them, and smiled for the camera. A few seconds later, the old grenade exploded exactly like it was designed to do. Both of the young men were killed instantly by the massive blast. The police found their mobile phone nearby on the ground. The phone survived the explosion, and the last photograph showed the two men smiling foolishly right before they ended their own lives for a simple picture. They made a terrible choice that cost them their lives.",
    dict: { "unexploded": "patlamamış", "hand grenade": "el bombası", "field": "alan/tarla", "Instead of": "yerine", "weapon": "silah", "metal pin": "metal pim", "exploding": "patlama", "smiled": "gülümsedi", "designed": "tasarlanmış", "instantly": "anında", "nearby": "yakında", "survived": "hayatta kaldı" },
    questions: [ {q:"Did the men find an unexploded hand grenade?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they call the police for help?", a_en:"No", a_tr:"Hayır"}, {q:"Did they pull the metal pin out of the grenade?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they hold the grenade and smile?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the grenade explode?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the two young men survive?", a_en:"No", a_tr:"Hayır"}, {q:"Did the phone survive the explosion?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_HeavySafeThief.mp3"] = [{
    text: "18. The Heavy Safe Thief. A foolish burglar broke into a wealthy office building late at night to steal money. He found a very large, heavy metal safe on the second floor. The heavy safe was locked tightly, and he could not open the thick steel door. He decided he needed to take the whole heavy box back to his house to break it open. But the safe weighed almost five hundred pounds. The thief dragged the heavy metal box to the top of the steep wooden stairs. He stood on the stairs below the safe and tried to pull it down gently toward himself. This was a completely terrible decision. Once the incredibly heavy metal box started sliding down the stairs, he could not stop it. The massive safe gained speed and crashed directly into him. It pushed him down the stairs and crushed him completely against the bottom wall. The thief died instantly. When the police finally opened the safe the next day, they found it was completely empty. He lost his life for absolutely no reward at all.",
    dict: { "burglar": "hırsız/soyguncu", "wealthy": "zengin", "safe": "kasa", "tightly": "sıkıca", "steel": "çelik", "weighed": "ağırlığındaydı", "dragged": "sürükledi", "steep": "dik", "stairs": "merdivenler", "sliding": "kayma", "gained": "kazandı", "speed": "hız", "crushed": "ezdi", "empty": "boş" },
    questions: [ {q:"Did the burglar break into an office building?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he find a heavy metal safe?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he open the thick steel door?", a_en:"No", a_tr:"Hayır"}, {q:"Did he try to pull the safe down the stairs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he stand below the heavy safe?", a_en:"Yes", a_tr:"Evet"}, {q:"Could he stop the safe from sliding?", a_en:"No", a_tr:"Hayır"}, {q:"Was the safe completely empty?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_DistractedDriver.mp3"] = [{
    text: "19. The Distracted Driver. A man was driving his car on a busy highway while trying to do many things at once. He was driving very fast, but he was not looking at the road ahead. He was eating a large sandwich with one hand, holding a mobile phone to his ear with his shoulder, and trying to read a thick book that was resting on his steering wheel! He thought he was a very skilled driver who could easily do four things at the exact same time. But the highway turned slightly to the right, and the man was completely distracted by his interesting book. He drove his car completely straight, moving right off the road at a very high speed. He crashed his car heavily into a large, solid tree and died instantly. He completely removed himself from the gene pool because he refused to pay attention to the simple task of safely driving a fast machine. It is very important to always watch the road when you drive a car. He made a deadly mistake on that day.",
    dict: { "highway": "otoyol", "ahead": "ileride", "shoulder": "omuz", "steering wheel": "direksiyon", "skilled": "yetenekli", "slightly": "hafifçe", "distracted": "dikkati dağılmış", "straight": "düz", "solid": "sert/katı", "gene pool": "gen havuzu", "pay attention": "dikkat etmek", "task": "görev" },
    questions: [ {q:"Was the man trying to do many things at once?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he eating a large sandwich?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he reading a thick book?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the highway turn slightly to the right?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the man looking at the road ahead?", a_en:"No", a_tr:"Hayır"}, {q:"Did he drive his car straight off the road?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he crash into a solid tree?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_FireworksHat.mp3"] = [{
    text: "20. The Fireworks Hat. A young man was celebrating a big holiday with his friends. They were drinking a lot of alcohol and having a very loud party in the backyard. The man wanted to make everyone laugh and show off his bravery. He found a very large, powerful, professional firework. This type of firework shoots a heavy, burning ball of fire high into the dark sky. The young man thought it would be a very funny joke to put the firework tube directly on top of his own head. His friends told him to stop, but he laughed and used a lighter to light the short fuse. He stood still, waiting for the firework to shoot up. But when the explosive launched, the massive downward force of the blast broke his neck instantly, and the explosion killed him. He wanted to be the funny center of attention at the party, but he made a deadly and stupid choice instead. You should never play with dangerous explosives like they are toys. He paid the highest price for his very silly joke.",
    dict: { "celebrating": "kutluyor", "bravery": "cesaret", "firework": "havai fişek", "burning": "yanan", "tube": "tüp/boru", "lighter": "çakmak", "fuse": "fitil", "launched": "fırladı", "downward force": "aşağı doğru kuvvet", "blast": "patlama", "attention": "ilgi/dikkat" },
    questions: [ {q:"Was the man celebrating a holiday?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to show off his bravery?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he put a powerful firework on his head?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his friends tell him to stop?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a lighter to light the fuse?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the downward force break his neck?", a_en:"Yes", a_tr:"Evet"}, {q:"Should you play with dangerous explosives?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["21_NightWaterSlide.mp3"] = [{
    text: "21. The Night Water Slide. Two teenage boys wanted to have a fun adventure late at night. They climbed over the tall security fence of a local water park that was closed for the winter season. There was no water running in the slides, and it was completely dark everywhere. They climbed all the way up the stairs to the highest and fastest water slide in the whole park. They sat down in the dry plastic tube and pushed themselves down into the darkness. But the park owners had done some important repairs. Because the park was closed, the workers had placed a heavy metal chain directly across the middle of the dark slide. The boys slid down very fast in the dark and could not see the massive danger ahead of them. They hit the heavy metal chain at full speed. They died because they decided to break the law and play in a dangerous, closed park in the complete darkness. They should have stayed safely at home that night. This was a terrible accident that was very easy to avoid.",
    dict: { "teenage": "genç/ergen", "adventure": "macera", "security fence": "güvenlik çiti", "season": "sezon/mevsim", "repairs": "tamiratlar", "chain": "zincir", "slid down": "aşağı kaydılar", "massive": "devasa", "danger": "tehlike", "break the law": "kanunu çiğnemek", "safely": "güvenle", "avoid": "kaçınmak" },
    questions: [ {q:"Did the boys climb over the security fence?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the water park closed for the winter?", a_en:"Yes", a_tr:"Evet"}, {q:"Was there water running in the slides?", a_en:"No", a_tr:"Hayır"}, {q:"Was there a heavy metal chain across the slide?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boys slide down in the dark?", a_en:"Yes", a_tr:"Evet"}, {q:"Could they see the chain in the dark?", a_en:"No", a_tr:"Hayır"}, {q:"Did they hit the chain at full speed?", a_en:"Yes", a_tr:"Evet"} ]
}];
